[package]
name = "prust-manual"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"

[build-dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
tempfile = "3.3.0"
zip-extract = "0.1.1"
url = "2.3.1"